version: "3.9"

services:
  frontend:
    build:
      context: "./marly-handmade-frontend"
    ports:
      - "5173:5173"
    networks:
      - app-networks
    depends_on:
      - backend

  backend:
    build:
      context: "./marly-handmade-backend"
    ports:
      - "8080:8080"
    networks:
      - app-networks
    environment:
      - URL_BD=${URL_BD}
      - USER_BD=${USER_BD}
      - PASSWORD_BD=${PASSWORD_BD}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - KEY_SEND_CORREO=${KEY_SEND_CORREO}

networks:
  app-networks:
    driver: bridge
